### PR TITLE
my eighth Assignment

### PR DESCRIPTION
**Pull request by JIT13CS**
my eighth assgn

### CODE REVIEW

**Review by yashubari — APPROVED** [review]

**Review by Pawan1005 — CHANGES_REQUESTED** [review]
add new line at end of every file

**Comment by JIT13CS** [comment]
it's not necessary ...as far as program is giving expected output no need to change things.Ya if anything wrong is written then you can tell

**Comment by Pawan1005** [comment]
you need to follow some kind of standards while writing a code

**Review by Snehal-113 — COMMENTED** [review]
plz make the changes requested by Pawan, so that we can merge your files

**Comment by JIT13CS** [comment]
my ninth and tenth assignment

**Comment by JIT13CS** [comment]
my 15th assignment

**Comment by JIT13CS** [comment]
my 16th Assignment

**Review by JIT13CS — COMMENTED** [review]
Added the updated assignment8

**Comment by JIT13CS** [comment]
my 18,19,20,21 Assignment

**Review by Pawan1005 — CHANGES_REQUESTED** [review]
how many time should we tell you to make proper indentation

**Comment by JIT13CS** [comment]
Now it's updated u didn't acknowledged i tried to update last time too if still there is any scope please specify because i am not getting which part you want me to update.But I think now it's updated.

**Comment by Pawan1005** [comment]
that is not only for 8th assignments its for all assignments

**Comment by JIT13CS** [comment]
My all other assignments are with proper indentation I have cross checked it and anything which is wrong like two input type in a line it's because after saving file, vs code is making it in one line and this is also correct..You please specify it I have crossed checked and not getting what to modify

**Comment by Pawan1005** [comment]
let it be check with vs code seating of spacing form next time use sublime code it great to do indentation

**Pull request merged**
