### PR TITLE
Renamed Assignment1_Preeti/ to Preeti/assignment1/

### PR DESCRIPTION
**Pull request by preetipie22**

### CODE REVIEW

**Review by Pawan1005 — COMMENTED** [review]
1. need indentation 
2. remove extra lines
3. check all files are not uploaded

**Comment by preetipie22** [comment]
> 1. need indentation
> 2. remove extra lines
> 3. check all files are not uploaded

@Pawan1005 didn't understand the third one.

**Comment by Pawan1005** [comment]
answer 1,2,3 are not there

**Comment by preetipie22** [comment]
> answer 1,2,3 are not there

@Pawan1005 Answer 1,2,3 are present. They are not visible in the changes, because they were already pushed to main branch, and in this PR, I've just moved them under a folder named "Preeti".
To view the files go to https://github.com/Snehal-113/MI-9-MEAN/tree/preeti/Preeti/assignment1

**Pull request merged**
